 version: '2'
 services:
  namenode:
   image: uhopper/hadoop-namenode:2.7.2
   hostname: namenode
   container_name: namenode
   networks: 
    - hadoop
   environment:
    - YARN_CONF_yarn_resourcemanager_hostname=172.24.0.6
    - CLUSTER_NAME=namenode


  datanode1:
   image: uhopper/hadoop-datanode:2.7.2
   hostname: datanode1
   container_name: datanode1
   networks: 
    - hadoop
   environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=172.24.0.6

  resourcemanager:
   image: uhopper/hadoop-resourcemanager:2.7.2
   hostname: resourcemanager
   container_name: resourcemanager
   #command: /create-folder.sh
   networks: 
    - hadoop
   ports:
    - 8088:8088
   expose:
    - 8032
   volumes:
    - ./resource:/resources
   environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=172.24.0.6
    - YARN_CONF_yarn_log___aggregation___enable=true


  nodemanager1:
   image: uhopper/hadoop-nodemanager:2.7.2
   hostname: nodemanager1
   container_name: nodemanager1
   ports:
    - 8042:8042
   networks: 
    - hadoop
   environment:
     - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
     - YARN_CONF_yarn_resourcemanager_hostname=172.24.0.6
     - YARN_CONF_yarn_log___aggregation___enable=true
     - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs

  spark:
   image: spark
   hostname: spark
   container_name: spark
   networks: 
    - hadoop
   expose:
    - 8042
    - 8020
   ports:
    - 9001:9001
   environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=172.24.0.6
   command: tail -f /var/log/dmesg

  historyserver:
    image: uhopper/hadoop-historyserver:2.7.2
    container_name: historyserver    
    hostname: historyserver
    networks:
      - hadoop
    ports:
    - 8081:8081
    environment:
     - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
     - YARN_CONF_yarn_resourcemanager_hostname=172.24.0.6



 networks:  
  hadoop:
   driver: bridge

